data<-c(45,47,50,52,48,47,49,53,51)
print("Ënter the mu value to be tested:")
mu<-scan()
n<-length(data)
print("enter the level of significance")
alpha<-scan()
std<-sd(data)
t<-t.test(data,mu=mu)
tablevalue<-round(qt(1-alpha/2, df=n-1),digits=3)
interval=round(t$conf.int,2)
print(paste("Confidence intervals :",interval[1],"&",interval[2]))
if(mu>interval[1] && mu<interval[2])
{
  print(paste("Ho is accepted i.e.; true mean is equal to ",mu))
}else print(paste("Ho is rejected altenatively h1 is accepted i.e.;true mean is not equal to ",mu))
